// <auto-generated />
using System;
using Himchistka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Himchistka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230811104329_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Himchistka.Models.DataBase.Client", b =>
                {
                    b.Property<int>("PhysicalPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("PhysicalPersonId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Employee", b =>
                {
                    b.Property<int>("PhysicalPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhysicalPersonId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delivery")
                        .HasColumnType("bit");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("money");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ReadyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReceptionPoint")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.PhysicalPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysicalPersons");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("money");

                    b.Property<string>("Defects")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("DirtStains")
                        .HasColumnType("bit");

                    b.Property<string>("FabricType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ResourcesExpention")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ServicePrice")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTimeSpent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Client", b =>
                {
                    b.HasOne("Himchistka.Models.DataBase.PhysicalPerson", "PhysicalPerson")
                        .WithOne("Client")
                        .HasForeignKey("Himchistka.Models.DataBase.Client", "PhysicalPersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Client_PhysicalPerson");

                    b.Navigation("PhysicalPerson");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Employee", b =>
                {
                    b.HasOne("Himchistka.Models.DataBase.PhysicalPerson", "PhysicalPerson")
                        .WithOne("Employee")
                        .HasForeignKey("Himchistka.Models.DataBase.Employee", "PhysicalPersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_PhysicalPerson");

                    b.Navigation("PhysicalPerson");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Order", b =>
                {
                    b.HasOne("Himchistka.Models.DataBase.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Client_Orders");

                    b.HasOne("Himchistka.Models.DataBase.Service", "Service")
                        .WithOne("Order")
                        .HasForeignKey("Himchistka.Models.DataBase.Order", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Service");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Product", b =>
                {
                    b.HasOne("Himchistka.Models.DataBase.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Service", b =>
                {
                    b.HasOne("Himchistka.Models.DataBase.Employee", "Employee")
                        .WithMany("Services")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Services");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Employee", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.PhysicalPerson", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Himchistka.Models.DataBase.Service", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
